Fix compile errors and second read error.
Included ctype.h to fix compiler error: "implicit declaration of function ‘isprint’"
Changed usb_close() to usb_reset() because otherwise the program only runs once before hitting "Fatal error> USB read failed" and needing to re-plug the device. ¯\_(ツ)_/¯